#%RAML 1.0 DataType
# types/task-response.raml
displayName: taskResponse
properties:
  taskId: integer
  taskPosition: integer
  task: string
  completed: boolean
  listId: integer
  creatorId: integer
  taskSince: datetime
