CREATE TABLE users
(
    userId INT NOT NULL AUTO_INCREMENT,
    userName VARCHAR(255) NOT NULL,
    userEmail VARCHAR(255) UNIQUE NOT NULL,
    userPassword BINARY(60) NOT NULL,
    userAdmin BOOLEAN NOT NULL DEFAULT 0,
    userSince TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (userId)
);
