#%RAML 1.0
title: List Manager
version: 0.8
baseUri: http://lists.hopto.org/
description: API for list management and collaboration
mediaType: [application/json]
types:
  login-createRequest: !include types/login-createRequest.raml

  user-createRequest: !include types/user-createRequest.raml
  Users-response: !include types/Users-response.raml
  user-response: !include types/user-response.raml
  user-changePassword: !include types/user-changePassword.raml

  list-createRequest: !include types/list-createRequest.raml
  Lists-response: !include types/Lists-response.raml
  list-response: !include types/list-response.raml

  task-createRequest: !include types/task-createRequest.raml
  Tasks-response: !include types/Tasks-response.raml
  task-response: !include types/task-response.raml

  collaborator-createRequest: !include types\collaborator-createRequest.raml
  Collaborators: !include types\Collaborators-response.raml
  collaborator-response: !include types\collaborators-response.raml

  createResourceResponse: !include types/createResourceResponse.raml

/login:
  put:
    body:
      application/json:
        example: !include examples/loginPutRequest.json
        type: login-createRequest
    responses:
      200:
        body:
          application/json:
            example: !include examples/loginPut200.json
      401:
        description: No recognized username/password combination.
        body:
          application/json:
            example: !include examples/loginPut401.json
  delete:
    responses:
      200:
        body:
          application/json:
            example: !include examples/success200.json
/Users:
  description: User management
  post:
    description: Create a new user
    body:
      application/json:
        type: user-createRequest
        example: !include examples/user-createRequest.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/loginPut200.json
            type: createResourceResponse
  get:
    description: Retrieve a set of users
    responses:
      200:
        body:
          application/json:
            type: Users-response

  /{uId}:
    description: Individual user record access

    get:
      description: Retrieve a single user record
      responses:
        200:
          body:
            application/json:
              type: user-response
        404:
          body:
            application/json:
              example: !include examples/error.json
    put:
      description: Update a single user record - but not the password
      body:
        application/json:
          type: user-createRequest
      responses:
        200:
          body:
            application/json:
              type: createResourceResponse
    delete:
      description: Delete a single user record
      responses:
        204:
          body:
            application/json:
              example: !include examples/error.json
    /password:
      description: Change password (requires admin or to be that user)
      put:
        body:
          application/json:
            type: user-changePassword
        responses:
          200:
            body:
              application/json:
                example: !include examples/success200.json
          401:
            body:
              application/json:
                example: !include examples/error.json
/Lists:
  description: Manage lists
  post:
    description: Create a new list
    body:
      application/json:
        type: list-createRequest
        example: !include examples/list-createRequest.json
    responses:
      200:
        body:
          application/json:
            example: !include examples/loginPut200.json
            type: createResourceResponse
  get:
    description: Retrieve a set of lists
    responses:
      200:
        body:
          application/json:
            type: Lists-response

  /{lId}:
    description: Indivdual list information (not the list's tasks)
    delete:
    get:
    put:
      description: Update an individual list (not the list's tasks)
      body:
        application/json:
          type: list-updateRequest
      responses:
        200:
          body:
            application/json:
              type: updateResourceResponse
